module.exports = {
  TABLE_NAME: process.env.TABLE_NAME,
  TWILIO_WHATSAPP_NUM: process.env.TWILIO_WHATSAPP_NUM,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  ACCESS_KEY: process.env.ACCESS_KEY,
  SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY,
  CONNECT_INSTANCE_ID: process.env.CONNECT_INSTANCE_ID,
  CONNECT_CONTACT_FLOW_ID: process.env.CONNECT_CONTACT_FLOW_ID,
  CONNECT_SOURCE_NUMBER: process.env.CONNECT_SOURCE_NUMBER,
  CONNECT_DESTINATION_NUMBER: process.env.CONNECT_DESTINATION_NUMBER
};
